---

- name: Get context mode
  cisco.asa.asa_command:
    commands:
      - "show mode"
  register: var_context

- name: Set asa_multi_context fact
  ansible.builtin.set_fact:
    asa_multi_context: false

- name: Set asa_multi_context fact on multiple context ASA
  ansible.builtin.set_fact:
    asa_multi_context: true
  when: '"multiple" in var_context.stdout[0]'


- name: Contexts present
  when: asa_multi_context
  block:

    - name: Discover contexts
      cisco.asa.asa_command:
        commands:
          - changeto system
          - show run context | inc context
      register: _contexts_names

    - name: Clean list of contexts
      ansible.builtin.set_fact:
        var_contexts_names: "{{ _contexts_names.stdout_lines[1] | reject('search', 'admin-context') | list }}"

    - name: Take backup of multiple mode ASA system context
      cisco.asa.asa_config:
        context: "system"
        backup: true
        backup_options:
          dir_path: "{{ cabc_backup_destination }}"
          filename: "{{ inventory_hostname }}-system.cfg"

    - name: Take backup of multiple mode ASA contexts
      cisco.asa.asa_config:
        context: "{{ item.split(' ')[1] }}"
        backup: true
        backup_options:
          dir_path: "{{ cabc_backup_destination }}"
          filename: "{{ inventory_hostname }}-{{ item.split(' ')[1] }}.cfg"
      loop:
        "{{ var_contexts_names }}"


- name: Take backup of single mode ASA
  cisco.asa.asa_config:
    backup: true
    backup_options:
      dir_path: "{{ cabc_backup_destination }}"
      filename: "{{ inventory_hostname }}.cfg"
  when: not asa_multi_context
